//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int EmpID { get; set; }

        [Required(ErrorMessage ="This field is required")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [EmailAddress]
        public string EmailID { get; set; }
        public string OfficeLocation { get; set; }
        public string Department { get; set; }
    }
}
